# Generated by Django 3.1.2 on 2020-10-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20201011_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='checkin',
            new_name='check_in',
        ),
    ]
